export const FETCH_TASK_LIST = 'TASKS::FETCH_TASK_LIST';
export const CREATE_TASK = 'TASKS::CREATE_TASK';
export const UPDATE_TASK = 'TASKS::UPDATE_TASK';
export const SELECT_TASK = 'TASKS::SELECT_TASK';
export const CLEAR_TASK = 'TASKS::CLEAR_TASK';
